server:
  port: 8802
spring:
  application:
    name: springclouddemoconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
